flags:
  text:
    integer-simple: false
packages:
- MoodlerLib/
- Moodler/
extra-deps:
- GLURaw-1.4.0.2
- GLUT-2.5.1.1
- JuicyPixels-3.2.5.2
- MonadRandom-0.4
- OpenGL-2.9.2.0
- OpenGLRaw-1.5.0.1
- PortMidi-0.1.4
- StateVar-1.1.0.0
- adjunctions-4.2.1
- ansi-terminal-0.6.2.1
- ansi-wl-pprint-0.6.7.2
- base-orphans-0.3.3
- bifunctors-5
- blaze-builder-0.4.0.1
- bmp-1.2.5.2
- comonad-4.2.6
- contravariant-1.3.1.1
- cpphs-1.19
- data-binary-ieee754-0.4.4
- distributive-0.4.4
- either-4.4.1
- exceptions-0.8.0.2
- extensible-exceptions-0.1.1.4
- free-4.12.1
- ghc-mtl-1.2.1.0
- ghc-paths-0.1.0.9
- gloss-1.9.2.1
- gloss-juicy-0.2
- gloss-rendering-1.9.2.1
- hashable-1.2.3.2
- hint-0.4.2.3
- hosc-0.14.1
- kan-extensions-4.2.2
- language-c-0.4.7
- lens-4.11
- mmorph-1.0.4
- monad-control-1.0.0.4
- mtl-2.1.3.1
- nats-1
- network-2.6.2.0
- optparse-applicative-0.11.0.2
- parallel-3.2.0.6
- polyparse-1.11
- prelude-extras-0.4
- primitive-0.6
- profunctors-5.1.1
- random-1.1
- reflection-1.5.2.1
- semigroupoids-5.0.0.2
- semigroups-0.16.2.2
- stm-2.4.4
- syb-0.5.1
- tagged-0.8.0.1
- temporary-1.2.0.3
- text-1.2.1.1
- transformers-base-0.4.4
- transformers-compat-0.4.0.3
- uniplate-1.6.12
- unordered-containers-0.2.5.1
- vector-0.10.12.3
- void-0.7
- zlib-0.6.1.1
resolver: ghc-7.8
